### ISSUE TITLE
Preprocessor_full.py import missing?

### ISSUE THREAD

**Issue by kanemoto117** [WOOSEUNGHOON/Centris-public#2]
Perhaps `import tlsh` is required in Preprocessor_full.py. 
Otherwise `tlsh.diffxlen()` will be always generate error and no score will be calculated.

**Comment by WOOSEUNGHOON** [comment]
@kanemoto117 Thank you. I have now confirmed that there was an error in the code owing to the refactoring process, and it has been corrected.

**Comment by kanemoto117** [comment]
Great!
